### ISSUE TITLE
_M4A1 has values of _M4A1GL (broma-weapon-list.sqf)

### ISSUE THREAD

**Issue by rundabollen** [broma-arma/BromA-Framework-A3-Addon#188]
https://github.com/broma-arma/BromA-Framework-A3-Addon/blob/1482e89ff910d9cf945bbd13d4a604c003e23abc/loadouts/content/broma-weapon-list.sqf#L630

`
_M4A1 = ["RH_m4a1_ris_m203",_30rnd556,_40mm];`

`_M4A1GL = ["RH_m4a1_ris_m203",_30rnd556,_40mm];
`
I assume _M4A1 is really supposed to be `rhs_weap_m4a1_carryhandle`.

**Comment by Royallle** [comment]
We should just delete any RH primary weapon reference apart from the handguns. The _M4A1 is overwritten with RHS classnames a couple of lines down in the weapon list.

**Comment by rundabollen** [comment]
Oh shit lmao. It's actually Robert Hammer and not RHS, I mentally added an S because it being Robert Hammer was just unthinkable 😂

**Comment by rundabollen** [comment]
Better fixed through big overhaul.

**Comment by Coryf88** [comment]
Going to keep this open, so it's not forgotten about.

**Comment by Coryf88** [comment]
Fixed in f76059f4ffece50145a85309b792ecbffccd8ca3
