### ISSUE TITLE
Framework ACE3 setting names

### ISSUE THREAD

**Issue by Coryf88** [broma-arma/BromA-Framework-A3-Addon#42]
**_Fix would break missions._**

ACE3 [Setting](https://github.com/Neefay/BromA-A3-Framework-Mark3/blob/master/mission/settings/mods-settings/ace3-settings.sqf) variable names could/do clash with ACE3's variable names.

**Examples:**
`ace_medical_enableScreams = ACE_Medical_screams;` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/ace3_plugin/functions/fn_postinit.sqf#L24)]
`ace_medical_preventInstaDeath = ACE_Medical_preventInstaDeath;` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/ace3_plugin/functions/fn_postinit.sqf#L28)]
`ace_medical_enableFor = ACE_Medical_enableFor;` [[Source](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/ace3_plugin/functions/fn_postinit.sqf#L35)]

**Comment by badkneegrow** [comment]
mission_ace_medical_screams etc.?

**Comment by Coryf88** [comment]
Another option would be to place all relevant settings into a single global variable. Less global _pollution_ and chance for variable clashing.

```
mission_ace_settings = [
	// Enables litter and discards upon treatment.
	// true/false
	true,

	// Delay for removing litter objects in seconds.
	// number (seconds) -1 is forever
	1000,

	// Enable screams of pain.
	// true/false
	true,
];
```

**Comment by badkneegrow** [comment]
a function for defaults and replace

[https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/ace3_plugin/functions/includes/settings.sqf](url)

**Comment by Coryf88** [comment]
Settings were removed sometime ago, due to settings moved to CBA.
