### ISSUE TITLE
Plugin: RadioFreq

### ISSUE THREAD

**Issue by Coryf88** [broma-arma/BromA-Framework-A3-Addon#63]
- [ ] Check usefulness of these global variables else where. Make private if unneeded, otherwise merge into an array:
`mission_valid_groups`, `mission_valid_groups_name`, `mission_valid_groups_BLU`, `mission_valid_groups_OP`, `mission_valid_groups_IND`, `mission_valid_groups_CIV`, `mission_valid_groups_name_BLU`, `mission_valid_groups_name_OP`, `mission_valid_groups_name_IND`, `mission_valid_groups_name_CIV`, `mission_used_freqs`.

The following global variables are used in the [Framework](https://github.com/Neefay/BromA-A3-Framework-Mark3/blob/master/mission/briefings/fn_loadBriefing.sqf) and currently cannot be renamed and needs to be [`publicVariable`](https://community.bistudio.com/wiki/publicVariable)d.
`mission_radiochannels_add_BLU`, `mission_radiochannels_add_OP`, `mission_radiochannels_add_IND`, `mission_radiochannels_add_CIV`, `mission_radiochannels_BLU`, `mission_radiochannels_OP`, `mission_radiochannels_IND`, `mission_radiochannels_CIV`

- [ ] Move [`mission_used_freqs pushBack _newFreq;`](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/radiofreq/functions/fn_postinit.sqf#L44) [after](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/radiofreq/functions/fn_postinit.sqf#L48) a unique `_newFreq` is created.

- [ ] Possibly change how frequencies are selected.
Could increment the frequencies per group.
* Zero Actual: 30
* Alpha Actual: 31
  * Alpha 1: 31.1
  * Alpha 2: 31.2
* Bravo Actual: 32
  * Bravo 1: 32.1
  * Bravo 2: 32.2

- [ ] Possibly automatically apply selected frequencies to units radio.

- [ ] Move [`publicVariable "mission_valid_groups"` ](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/radiofreq/functions/fn_postinit.sqf#L65) after [`forEach`](https://github.com/Neefay/BromA-Framework-A3-Addon/blob/master/plugins/radiofreq/functions/fn_postinit.sqf#L74) (If left as a global variable and deemed should also remain publicVariable'd)

**Comment by badkneegrow** [comment]
- [ ] Parameter / option to not scramble frequencies
   - [ ] Agree on default frequencies (LR ~50; Alpha SR ~101;Bravo SR ~102; etc.)

**Comment by Neefay** [comment]
This plugin is extremely inefficient and completely fails to properly utilize TFAR and its settings. As soon as we get some results from Armastock, it's going to be phased out entirely.

**Comment by Coryf88** [comment]
[Structure Spreadsheet](https://docs.google.com/spreadsheets/d/1DFSOeS7Dqnoav40NnUgCDmB4X0r_DaVFaLqSoFCbQGM/edit?usp=sharing)

Alpha 1 - Rifleman (blu_1_1_2)
![image](https://github.com/user-attachments/assets/9802ce8b-8808-44b0-816e-e2659e807160)

Short Range Nets are clickable links that changes CH6's frequency to the frequency used by the clicked group/squad.

I still need to sort the short range channels and change CH# to Channel # or vice versa.
