### ISSUE TITLE
Mission end causing desync with ~15 people

### ISSUE THREAD

**Issue by Tennessee-Timmy** [broma-arma/BromA-Framework-A3-Addon#68]
Come armastock, this will be a bigger problem.

**Comment by badkneegrow** [comment]
http://arma3.faith/sharex/dsync.webm

**Comment by Coryf88** [comment]
I'd assume the cause of this is OCAP exporting.

**Comment by Neefay** [comment]
We should probably disable OCAP for Armastock.

**Comment by Coryf88** [comment]
Armastock done. End of mission anyways. Probably OCAP.
