### ISSUE TITLE
Loadouts not given to respawned players or players who join faster than the server

### ISSUE THREAD

**Issue by geroge-011** [broma-arma/BromA-Framework-A3-Addon#9]
When we all respawned at once. seems like

_faction = [(side player), "faction"] call BRM_FMK_fnc_getSideInfo;

Will give the wrong side whenever the unit is dead or whenever the player loads into the game before the server (server does not have map/mission loaded and player who has the map/mission loaded on the game will load faster than the server.)

http://arma3.faith/respawnbug.webm

**Comment by xJenny99x** [comment]
Also I believe that we got shot down by a manpad. Because those are in the mission (rare) and mi-8 does not have a warning system.

**Comment by badkneegrow** [comment]
http://arma3.faith/sharex/respawnbug.webm

**Comment by Coryf88** [comment]
I haven't seen this occur since and the respawn system has pretty much been rewritten, so assuming fixed.
